/**
 * Standardized internal spec markdown template (deterministic, no I/O).
 */

export type SpecTemplateInput = {
  id: string;            // e.g. TC-12345
  title: string;
  sourceFile: string;    // input file path as provided (relative or absolute)
  normalizedAt: string;  // ISO timestamp
  summary: string;
  steps: string[];
  expectedResults: string[];
  rawInput: string;
};

export function buildSpecMarkdown(input: SpecTemplateInput): string {
  const steps = input.steps.length > 0 ? input.steps : ['TBD'];
  const expected = input.expectedResults.length > 0 ? input.expectedResults : ['TBD'];

  const stepLines = steps.map((step, index) => `${index + 1}. ${step}`).join('\n');
  const expectedLines = expected.map((item, index) => `${index + 1}. ${item}`).join('\n');

  return `# ${input.id} - ${input.title}

## Metadata

- Source: local-file
- Source file: ${input.sourceFile}
- Normalized at: ${input.normalizedAt}

## Summary

${input.summary}

## Preconditions

- TBD

## Steps

${stepLines}

## Expected Results

${expectedLines}

## Notes

- Generated by qa-agents normalize-spec.
- Review and complete this spec before using it for automation generation.

## Raw Input

\`\`\`txt
${input.rawInput}
\`\`\`
`;
}
